# Generated by Django 4.2.5 on 2023-09-05 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userdetails_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
